### ISSUE TITLE
Invalid behaviour of `availableBetween`

### ISSUE THREAD

**Issue by Grushenko** [Delebrith/APSI-enrollment#13]
Available between search criteria for places and users is not working for ISO 8601 strings.
Example request: 
`http://localhost:8080/places?searchQuery=availableBetween=2020-04-29T08:00:00Z;2020-04-29T10:00:00Z`. That is caused by invalid DateFormatter (with no support for timezones). Also SearchQuery regex should include `.` character as it is included in date strings.

**Comment by Delebrith** [comment]
Server does not support timezones. Please, for now, use dates without timezone

**Comment by Grushenko** [comment]
The thing is it does (at lest do valid conversion in DTOs to valid iso strings with timezone marker) except from `availableBetween` searchQuery. I'll prepare fix for this in a moment.
